version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai-toolbox-backend
    ports:
      - "8000:8000"
    env_file:
      - .env.docker.local
    environment:
      # 覆盖或补充环境变量
      - PYTHONPATH=/app
    volumes:
      # 开发时可以挂载代码目录进行热重载
      # - ./backend:/app
      - backend_logs:/app/logs
    networks:
      - ai-toolbox-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ai-toolbox-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ai-toolbox-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# 网络配置
networks:
  ai-toolbox-network:
    driver: bridge
    name: ai-toolbox-network

# 数据卷配置
volumes:
  backend_logs:
    driver: local
    name: ai-toolbox-backend-logs