# Docker Compose配置文件 (兼容版本1和2)
# 移除了version字段以兼容旧版本Docker Compose

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5173:5173"
    env_file:
      - .env.docker
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=5173
    # 简化的健康检查，兼容旧版本
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

# 移除了networks配置以兼容旧版本
# 移除了volumes配置（如不需要持久化存储）