version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - ai-toolbox-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5173:5173"
    env_file:
      - .env.docker
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=5173
    networks:
      - ai-toolbox-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ai-toolbox-network:
    driver: bridge

volumes:
  backend_data:
    driver: local